version: '3.9'

services:
  # MySQL
  mysql:
    image: mysql
    restart: always
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'docker_root_pw'
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes: # Keep our data alive when restart.
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
    cap_add:
      - SYS_NICE # CAP_SYS_NICE

  # Redis service
  redis:
    image: redis
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - $REDIS_PORT:$REDIS_PORT
    volumes:
      - $PWD/redis-data:/var/lib/redis

  # backend API
  face-ai-api:
    container_name: api
    build: . # Build from the local Dockerfile
    depends_on:
      - mysql
      - redis
    stdin_open: true
    tty: true
    command: yarn serve
    working_dir: /usr/src/face-ai-api
    ports:
      - '3030:3030'
    volumes:
      - ./:/usr/src/face-ai-api
      - /usr/src/face-ai-api/node_modules

volumes:
  db-config:
  db-data:
