version: '3.9'

services:
  # backend API
  face-ai-api:
    container_name: backend
    #image: node: 16.4.0
    build: . # Build from the local Dockerfile
    command: yarn serve
    working_dir: /usr/src/face-ai-api
    environment:
      MYSQL_ROOT_PASSWORD: 'docker_mysql_pw'
      MYSQL_DATABASE: 'face_ai_docker'
      MYSQL_USER: 'face_ai'
      MYSQL_PASSWORD: 'face_ai_pw'
      MYSQL_HOST: 'mysql'
    links:
      - mysql
    ports:
      - '3030:3030'
    volumes:
      - ./:/usr/src/face-ai-api
      - /usr/src/face-ai-api/node_modules

  # MySQL
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'docker_mysql_pw'
      MYSQL_DATABASE: 'face_ai_docker'
      MYSQL_USER: 'face_ai'
      MYSQL_PASSWORD: 'face_ai_pw'
    ports:
      - '3306:3306'
